name:                microfactor
version:             0.1.0.0
# github:              "username/microfactor"
license:             WTFPL
author:              "Andreas Bergmaier"
maintainer:          "andreas.bergmaier@hm.edu"
copyright:           "2018 A. Bergmaier"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/microfactor#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- parsec

library:
  source-dirs: src

executables:
  microfactor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - microfactor

tests:
  microfactor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - microfactor
    - tasty
    - tasty-hunit
