name:                microfactor
version:             0.1.0.0
github:              ob-fun-ws18/microFactor
license:             WTFPL
author:              "Andreas Bergmaier"
maintainer:          "andreas.bergmaier@hm.edu"
copyright:           "2018 A. Bergmaier"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            An implementation of the Factor programming lanugage with a feature set reduced to be suitable for microcontrollers
category:            Compilers/Interpreters, Interpreter

description:         Please see the README on GitHub at <https://github.com/ob-fun-ws18/microFactor#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- ansi-terminal
- parsec
- mtl

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-name-shadowing

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstrainedClassMethods
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications

library:
  source-dirs: src

executables:
  microfactor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - microfactor

tests:
  microfactor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - microfactor
    - tasty
    - tasty-hunit
